### ISSUE TITLE
sql file

### ISSUE THREAD

**Issue by R1NTS1** [yonardpauly/Register_Login_Component#1]
Hi! @yonardpauly 
Can you please send the sql file. I want to get to try your code.

**Comment by yonardpauly** [comment]
The sql file is already included in the folder :)

**Comment by yonardpauly** [comment]
OMG I forgot sorry. Later I will update TY

**Comment by R1NTS1** [comment]
Okay. Thx! :D

**Comment by yonardpauly** [comment]
Sorry for being late in uploading sql file. I was busy yesterday and I was not here at my apartment. Hope my project helps you a lot. Thank you :)

**Comment by R1NTS1** [comment]
Thank you :)
